-- =================================================================
-- Migration: Projects Feature Enhancement
-- Target:    supabase/dev (Postgres 15 / Supabase)
-- Date:      2026-05-19
-- Author:    roofing-webapp
--
-- SAFE TO RE-RUN:
--   ADD COLUMN, CREATE TABLE, CREATE INDEX all use IF NOT EXISTS.
--   UNIQUE constraint, FK constraints, and ADD GENERATED BY DEFAULT AS
--   IDENTITY are wrapped in idempotent DO $$ blocks.
--
-- ADDITIVE ONLY — no existing columns or rows are removed.
-- The legacy `projects.status` text column is kept for backward compat.
-- =================================================================

BEGIN;

-- -----------------------------------------------------------------
-- PHASE 1 — project_status lookup table
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."project_status" (
    "id"          bigint                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        text                        NOT NULL,
    "description" text,
    "created_at"  timestamp with time zone    NOT NULL DEFAULT now(),
    "updated_at"  timestamp without time zone          DEFAULT now()
);

ALTER TABLE "public"."project_status" OWNER TO "postgres";
COMMENT ON TABLE "public"."project_status" IS 'Lookup table for project lifecycle statuses.';

INSERT INTO "public"."project_status" ("id", "name", "description") VALUES
  (1, 'Planning',  'Project is being planned — no work has started yet.'),
  (2, 'Active',    'Project is currently in progress.'),
  (3, 'On Hold',   'Project has been temporarily paused.'),
  (4, 'Completed', 'Project has been finished successfully.'),
  (5, 'Cancelled', 'Project was cancelled before completion.')
ON CONFLICT (id) DO NOTHING;

-- Reseed identity sequence above the highest inserted id
ALTER TABLE "public"."project_status" ALTER COLUMN "id" RESTART WITH 6;

-- -----------------------------------------------------------------
-- PHASE 2 — project_source lookup table
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."project_source" (
    "id"          bigint                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        text                        NOT NULL,
    "description" text,
    "created_at"  timestamp with time zone    NOT NULL DEFAULT now(),
    "updated_at"  timestamp without time zone          DEFAULT now()
);

ALTER TABLE "public"."project_source" OWNER TO "postgres";
COMMENT ON TABLE "public"."project_source" IS 'Lookup table for how a project was sourced or acquired.';

INSERT INTO "public"."project_source" ("id", "name", "description") VALUES
  (1, 'Referral',                 'Project came from a customer or partner referral.'),
  (2, 'Repeat Customer',          'Returning customer from a previous roofing job.'),
  (3, 'Quote Request / Web Form', 'Customer submitted an online quote request form.'),
  (4, 'Walk-in',                  'Customer contacted the company directly.'),
  (5, 'Social Media',             'Project originated through social media channels.'),
  (6, 'Other',                    'Source not covered by the options above.')
ON CONFLICT (id) DO NOTHING;

-- Reseed identity sequence above the highest inserted id
ALTER TABLE "public"."project_source" ALTER COLUMN "id" RESTART WITH 7;

-- -----------------------------------------------------------------
-- PHASE 3 — Enhance projects table: status FK + source FK + rich text
-- -----------------------------------------------------------------

-- project_status_id FK
ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "project_status_id" bigint
  REFERENCES "public"."project_status"("id") ON DELETE SET NULL;

COMMENT ON COLUMN "public"."projects"."project_status_id"
  IS 'FK to project_status. Replaces the raw status text column over time.';

-- Back-fill status FK from existing raw text values (case-insensitive match)
UPDATE "public"."projects" p
SET    "project_status_id" = ps.id
FROM   "public"."project_status" ps
WHERE  LOWER(TRIM(p.status)) = LOWER(ps.name)
  AND  p.project_status_id IS NULL;

-- source_id FK
ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "source_id" bigint
  REFERENCES "public"."project_source"("id") ON DELETE SET NULL;

COMMENT ON COLUMN "public"."projects"."source_id"
  IS 'FK to project_source. Tracks how this project was acquired.';

-- Rich text columns
ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "notes"       text;

COMMENT ON COLUMN "public"."projects"."description"
  IS 'Short summary of the project scope.';
COMMENT ON COLUMN "public"."projects"."notes"
  IS 'Internal notes visible only to the team.';

-- -----------------------------------------------------------------
-- PHASE 3b — Pre-existing columns: enforce service NOT NULL + comments
--
-- The following columns already exist in the original projects table
-- (from the base schema.sql). This phase documents them and enforces
-- the required business rules.
--
--   created_at  timestamptz  NOT NULL DEFAULT now()
--   updated_at  timestamp    NOT NULL DEFAULT now()  (trigger in Phase 9)
--   customer    bigint NULL  FK → customer(id)       optional
--   service     bigint NULL  FK → service(id)        optional
-- -----------------------------------------------------------------

COMMENT ON COLUMN "public"."projects"."created_at"
  IS 'Timestamp when this project was created. Set automatically on INSERT.';
COMMENT ON COLUMN "public"."projects"."updated_at"
  IS 'Timestamp of the last update. Automatically maintained by the update_projects_updated_at trigger.';
COMMENT ON COLUMN "public"."projects"."customer"
  IS 'Optional FK to customer(id). A project may exist before a customer is assigned.';
COMMENT ON COLUMN "public"."projects"."service"
  IS 'Optional FK to service(id). Links the project to a service type.';

-- -----------------------------------------------------------------
-- PHASE 4 — project_number: UNIQUE constraint + auto-increment identity
-- -----------------------------------------------------------------

-- Idempotent UNIQUE constraint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname    = 'projects_project_number_key'
      AND  conrelid   = 'public.projects'::regclass
  ) THEN
    ALTER TABLE public.projects
      ADD CONSTRAINT projects_project_number_key UNIQUE (project_number);
  END IF;
END;
$$;

-- Idempotent GENERATED BY DEFAULT AS IDENTITY
-- NOTE: Will fail if project_number already has a DEFAULT set from a prior partial run.
DO $$
DECLARE
  v_attidentity char;
BEGIN
  SELECT a.attidentity INTO v_attidentity
  FROM   pg_attribute  a
  JOIN   pg_class      c ON c.oid = a.attrelid
  JOIN   pg_namespace  n ON n.oid = c.relnamespace
  WHERE  n.nspname = 'public'
    AND  c.relname = 'projects'
    AND  a.attname = 'project_number';

  IF v_attidentity IS NULL OR v_attidentity = '' THEN
    ALTER TABLE public.projects
      ALTER COLUMN project_number ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END;
$$;

-- Restart sequence above current max to avoid conflicts with pre-existing rows
DO $$
DECLARE
  v_next bigint;
BEGIN
  SELECT COALESCE(MAX(project_number), 0) + 1 INTO v_next
  FROM   public.projects;

  EXECUTE format(
    'ALTER TABLE public.projects ALTER COLUMN project_number RESTART WITH %s',
    v_next
  );
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 5 — Google Drive columns
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "drive_folder_id"   text,
  ADD COLUMN IF NOT EXISTS "drive_folder_name" text,
  ADD COLUMN IF NOT EXISTS "drive_folder_url"  text;

COMMENT ON COLUMN "public"."projects"."drive_folder_id"
  IS 'Google Drive folder resource ID. NULL when no folder is linked.';
COMMENT ON COLUMN "public"."projects"."drive_folder_name"
  IS 'Cached Drive folder display name. Avoids an extra API call for UI rendering.';
COMMENT ON COLUMN "public"."projects"."drive_folder_url"
  IS 'Full Google Drive folder URL (https://drive.google.com/drive/folders/...).';

-- -----------------------------------------------------------------
-- PHASE 6 — project_assignee junction table
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."project_assignee" (
    "project_id"  uuid                     NOT NULL,
    "user_id"     uuid                     NOT NULL,
    "assigned_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "project_assignee_pkey" PRIMARY KEY ("project_id", "user_id")
);

ALTER TABLE "public"."project_assignee" OWNER TO "postgres";

COMMENT ON TABLE  "public"."project_assignee"
  IS 'Maps auth users to projects they are assigned to.';
COMMENT ON COLUMN "public"."project_assignee"."user_id"
  IS 'References auth.users(id). The signed-in app user assigned to this project.';
COMMENT ON COLUMN "public"."project_assignee"."assigned_at"
  IS 'Timestamp when the user was assigned to this project.';

-- project_assignee → projects FK (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'project_assignee_project_id_fkey'
      AND  conrelid = 'public.project_assignee'::regclass
  ) THEN
    ALTER TABLE public.project_assignee
      ADD CONSTRAINT project_assignee_project_id_fkey
      FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;
  END IF;
END;
$$;

-- project_assignee → auth.users FK (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'project_assignee_user_id_fkey'
      AND  conrelid = 'public.project_assignee'::regclass
  ) THEN
    ALTER TABLE public.project_assignee
      ADD CONSTRAINT project_assignee_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 7 — Link invoice & quote to project
-- -----------------------------------------------------------------

-- invoice.project_id
ALTER TABLE "public"."invoice"
  ADD COLUMN IF NOT EXISTS "project_id" uuid;

COMMENT ON COLUMN "public"."invoice"."project_id"
  IS 'Optional FK to projects. Links this invoice to a project.';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'invoice_project_id_fkey'
      AND  conrelid = 'public.invoice'::regclass
  ) THEN
    ALTER TABLE public.invoice
      ADD CONSTRAINT invoice_project_id_fkey
      FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
  END IF;
END;
$$;

-- quote.project_id
ALTER TABLE "public"."quote"
  ADD COLUMN IF NOT EXISTS "project_id" uuid;

COMMENT ON COLUMN "public"."quote"."project_id"
  IS 'Optional FK to projects. Links this quote to a project.';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'quote_project_id_fkey'
      AND  conrelid = 'public.quote'::regclass
  ) THEN
    ALTER TABLE public.quote
      ADD CONSTRAINT quote_project_id_fkey
      FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 8 — Indexes
-- -----------------------------------------------------------------

CREATE INDEX IF NOT EXISTS "idx_projects_project_status_id"
  ON "public"."projects" ("project_status_id");

CREATE INDEX IF NOT EXISTS "idx_projects_source_id"
  ON "public"."projects" ("source_id");

CREATE INDEX IF NOT EXISTS "idx_projects_customer"
  ON "public"."projects" ("customer");

CREATE INDEX IF NOT EXISTS "idx_projects_service"
  ON "public"."projects" ("service");

-- Partial index — only rows with a linked Drive folder
CREATE INDEX IF NOT EXISTS "idx_projects_drive_folder_id"
  ON "public"."projects" ("drive_folder_id")
  WHERE "drive_folder_id" IS NOT NULL;

-- Partial indexes for FK columns that will mostly be NULL initially
CREATE INDEX IF NOT EXISTS "idx_invoice_project_id"
  ON "public"."invoice" ("project_id")
  WHERE "project_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_quote_project_id"
  ON "public"."quote" ("project_id")
  WHERE "project_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_project_assignee_user_id"
  ON "public"."project_assignee" ("user_id");

-- -----------------------------------------------------------------
-- PHASE 9 — updated_at trigger on projects
-- (reuses the existing update_updated_at_column() function)
-- -----------------------------------------------------------------

CREATE OR REPLACE TRIGGER "update_projects_updated_at"
  BEFORE UPDATE ON "public"."projects"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();

-- -----------------------------------------------------------------
-- PHASE 10 — Row Level Security
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_status"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_source"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_assignee" ENABLE ROW LEVEL SECURITY;

-- projects — full CRUD for authenticated users
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'projects'
      AND  policyname = 'Enable all operations for authenticated users only'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable all operations for authenticated users only"
        ON public.projects
        TO authenticated
        USING (true)
        WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

-- project_status — read-only for authenticated users (managed via admin)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'project_status'
      AND  policyname = 'Enable read for authenticated users'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable read for authenticated users"
        ON public.project_status
        FOR SELECT
        TO authenticated
        USING (true)
    $policy$;
  END IF;
END;
$$;

-- project_source — read-only for authenticated users
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'project_source'
      AND  policyname = 'Enable read for authenticated users'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable read for authenticated users"
        ON public.project_source
        FOR SELECT
        TO authenticated
        USING (true)
    $policy$;
  END IF;
END;
$$;

-- project_assignee — full CRUD for authenticated users
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'project_assignee'
      AND  policyname = 'Enable all operations for authenticated users only'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable all operations for authenticated users only"
        ON public.project_assignee
        TO authenticated
        USING (true)
        WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

COMMIT;
