-- =================================================================
-- Migration: Projects Feature Enhancement
-- Target:    supabase/dev (Postgres 15 / Supabase)
-- Date:      2026-05-19
-- Author:    roofing-webapp
--
-- SAFE TO RE-RUN:
--   ADD COLUMN, CREATE TABLE, CREATE INDEX all use IF NOT EXISTS.
--   UNIQUE constraint, FK constraints, and ADD GENERATED BY DEFAULT AS
--   IDENTITY are wrapped in idempotent DO $$ blocks.
--
-- ADDITIVE ONLY — no existing columns or rows are removed.
-- The legacy `projects.status` text column is kept for backward compat.
-- =================================================================

BEGIN;

-- -----------------------------------------------------------------
-- PHASE 1 — project_status lookup table
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."project_status" (
    "id"          bigint                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        text                        NOT NULL,
    "description" text,
    "created_at"  timestamp with time zone    NOT NULL DEFAULT now(),
    "updated_at"  timestamp without time zone          DEFAULT now()
);

ALTER TABLE "public"."project_status" OWNER TO "postgres";
COMMENT ON TABLE "public"."project_status" IS 'Lookup table for project lifecycle statuses.';

INSERT INTO "public"."project_status" ("id", "name", "description") VALUES
  (1, 'Lead',                    'Potential customer — not yet committed.'),
  (2, 'Estimate Sent',           'Quote/proposal delivered, awaiting customer response.'),
  (3, 'Approved / Booked',       'Customer said yes — job is scheduled.'),
  (4, 'In Progress',             'Crew is actively working on the roof.'),
  (5, 'Inspection / Punch List', 'Work done — final walkthrough or touch-ups needed.'),
  (6, 'Invoice Sent',            'Waiting on payment.'),
  (7, 'Completed',               'Paid and closed.')
ON CONFLICT (id) DO NOTHING;

-- Reseed identity sequence above the highest inserted id
ALTER TABLE "public"."project_status" ALTER COLUMN "id" RESTART WITH 8;

-- -----------------------------------------------------------------
-- PHASE 2 — project_source lookup table
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."project_source" (
    "id"          bigint                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        text                        NOT NULL,
    "description" text,
    "created_at"  timestamp with time zone    NOT NULL DEFAULT now(),
    "updated_at"  timestamp without time zone          DEFAULT now()
);

ALTER TABLE "public"."project_source" OWNER TO "postgres";
COMMENT ON TABLE "public"."project_source" IS 'Lookup table for how a project was sourced or acquired.';

INSERT INTO "public"."project_source" ("id", "name", "description") VALUES
  (1, 'Referral',                 'Project came from a customer or partner referral.'),
  (2, 'Repeat Customer',          'Returning customer from a previous roofing job.'),
  (3, 'Quote Request / Web Form', 'Customer submitted an online quote request form.'),
  (4, 'Walk-in',                  'Customer contacted the company directly.'),
  (5, 'Social Media',             'Project originated through social media channels.'),
  (6, 'Other',                    'Source not covered by the options above.')
ON CONFLICT (id) DO NOTHING;

-- Reseed identity sequence above the highest inserted id
ALTER TABLE "public"."project_source" ALTER COLUMN "id" RESTART WITH 7;

-- -----------------------------------------------------------------
-- PHASE 3 — Enhance projects table: status FK + source FK + rich text
-- -----------------------------------------------------------------

-- project_status_id FK
ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "project_status_id" bigint
  REFERENCES "public"."project_status"("id") ON DELETE SET NULL;

COMMENT ON COLUMN "public"."projects"."project_status_id"
  IS 'FK to project_status. Replaces the raw status text column over time.';

-- Back-fill status FK from existing raw text values (case-insensitive match).
-- NOTE: The new status names (Lead, Estimate Sent, …, Completed) differ from
-- the legacy text values that may exist in projects.status. Only rows where the
-- text exactly matches (e.g. 'Completed' → id 7) will be back-filled.
-- Remaining rows will have project_status_id = NULL and should be assigned
-- manually via Supabase Studio after migration.
UPDATE "public"."projects" p
SET    "project_status_id" = ps.id
FROM   "public"."project_status" ps
WHERE  LOWER(TRIM(p.status)) = LOWER(ps.name)
  AND  p.project_status_id IS NULL;

-- source_id FK
ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "source_id" bigint
  REFERENCES "public"."project_source"("id") ON DELETE SET NULL;

COMMENT ON COLUMN "public"."projects"."source_id"
  IS 'FK to project_source. Tracks how this project was acquired.';

-- Rich text columns
ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "notes"       text;

COMMENT ON COLUMN "public"."projects"."description"
  IS 'Short summary of the project scope.';
COMMENT ON COLUMN "public"."projects"."notes"
  IS 'Internal notes visible only to the team.';

-- -----------------------------------------------------------------
-- PHASE 3b — Pre-existing columns: enforce service NOT NULL + comments
--
-- The following columns already exist in the original projects table
-- (from the base schema.sql). This phase documents them and enforces
-- the required business rules.
--
--   created_at  timestamptz  NOT NULL DEFAULT now()
--   updated_at  timestamp    NOT NULL DEFAULT now()  (trigger in Phase 9)
--   customer    bigint NULL  FK → customer(id)       optional
--   service     bigint NULL  FK → service(id)        optional
-- -----------------------------------------------------------------

COMMENT ON COLUMN "public"."projects"."created_at"
  IS 'Timestamp when this project was created. Set automatically on INSERT.';
COMMENT ON COLUMN "public"."projects"."updated_at"
  IS 'Timestamp of the last update. Automatically maintained by the update_projects_updated_at trigger.';
COMMENT ON COLUMN "public"."projects"."customer"
  IS 'Optional FK to customer(id). A project may exist before a customer is assigned.';
COMMENT ON COLUMN "public"."projects"."service"
  IS 'Optional FK to service(id). Links the project to a service type.';

-- -----------------------------------------------------------------
-- PHASE 4 — project_number: UNIQUE constraint + auto-increment identity
-- -----------------------------------------------------------------

-- Idempotent UNIQUE constraint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname    = 'projects_project_number_key'
      AND  conrelid   = 'public.projects'::regclass
  ) THEN
    ALTER TABLE public.projects
      ADD CONSTRAINT projects_project_number_key UNIQUE (project_number);
  END IF;
END;
$$;

-- Idempotent GENERATED BY DEFAULT AS IDENTITY + sequence restart.
-- Uses information_schema.columns.identity_generation (plain text, NULL vs
-- 'BY DEFAULT'/'ALWAYS') to avoid the "char" vs char(1) type ambiguity that
-- made pg_attribute.attidentity unreliable in PL/pgSQL variable comparisons.
DO $$
DECLARE
  v_identity_gen text;
  v_next         bigint;
BEGIN
  SELECT identity_generation INTO v_identity_gen
  FROM   information_schema.columns
  WHERE  table_schema = 'public'
    AND  table_name   = 'projects'
    AND  column_name  = 'project_number';

  IF v_identity_gen IS NULL THEN
    ALTER TABLE public.projects
      ALTER COLUMN project_number ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;

  -- Re-read after the potential ADD to confirm identity before RESTART WITH
  SELECT identity_generation INTO v_identity_gen
  FROM   information_schema.columns
  WHERE  table_schema = 'public'
    AND  table_name   = 'projects'
    AND  column_name  = 'project_number';

  IF v_identity_gen IS NOT NULL THEN
    SELECT COALESCE(MAX(project_number), 0) + 1 INTO v_next
    FROM   public.projects;

    EXECUTE format(
      'ALTER TABLE public.projects ALTER COLUMN project_number RESTART WITH %s',
      v_next
    );
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 5 — Google Drive columns
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "drive_folder_id"   text,
  ADD COLUMN IF NOT EXISTS "drive_folder_name" text,
  ADD COLUMN IF NOT EXISTS "drive_folder_url"  text;

COMMENT ON COLUMN "public"."projects"."drive_folder_id"
  IS 'Google Drive folder resource ID. NULL when no folder is linked.';
COMMENT ON COLUMN "public"."projects"."drive_folder_name"
  IS 'Cached Drive folder display name. Avoids an extra API call for UI rendering.';
COMMENT ON COLUMN "public"."projects"."drive_folder_url"
  IS 'Full Google Drive folder URL (https://drive.google.com/drive/folders/...).';

-- -----------------------------------------------------------------
-- PHASE 6 — project_assignee junction table
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."project_assignee" (
    "project_id"  uuid                     NOT NULL,
    "user_id"     uuid                     NOT NULL,
    "assigned_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "project_assignee_pkey" PRIMARY KEY ("project_id", "user_id")
);

ALTER TABLE "public"."project_assignee" OWNER TO "postgres";

COMMENT ON TABLE  "public"."project_assignee"
  IS 'Maps auth users to projects they are assigned to.';
COMMENT ON COLUMN "public"."project_assignee"."user_id"
  IS 'References auth.users(id). The signed-in app user assigned to this project.';
COMMENT ON COLUMN "public"."project_assignee"."assigned_at"
  IS 'Timestamp when the user was assigned to this project.';

-- project_assignee → projects FK (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'project_assignee_project_id_fkey'
      AND  conrelid = 'public.project_assignee'::regclass
  ) THEN
    ALTER TABLE public.project_assignee
      ADD CONSTRAINT project_assignee_project_id_fkey
      FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;
  END IF;
END;
$$;

-- project_assignee → auth.users FK (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'project_assignee_user_id_fkey'
      AND  conrelid = 'public.project_assignee'::regclass
  ) THEN
    ALTER TABLE public.project_assignee
      ADD CONSTRAINT project_assignee_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 7 — Link invoice & quote to project
-- -----------------------------------------------------------------

-- invoice.project_id
ALTER TABLE "public"."invoice"
  ADD COLUMN IF NOT EXISTS "project_id" uuid;

COMMENT ON COLUMN "public"."invoice"."project_id"
  IS 'Optional FK to projects. Links this invoice to a project.';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'invoice_project_id_fkey'
      AND  conrelid = 'public.invoice'::regclass
  ) THEN
    ALTER TABLE public.invoice
      ADD CONSTRAINT invoice_project_id_fkey
      FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
  END IF;
END;
$$;

-- quote.project_id
ALTER TABLE "public"."quote"
  ADD COLUMN IF NOT EXISTS "project_id" uuid;

COMMENT ON COLUMN "public"."quote"."project_id"
  IS 'Optional FK to projects. Links this quote to a project.';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'quote_project_id_fkey'
      AND  conrelid = 'public.quote'::regclass
  ) THEN
    ALTER TABLE public.quote
      ADD CONSTRAINT quote_project_id_fkey
      FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 8 — Indexes
-- -----------------------------------------------------------------

CREATE INDEX IF NOT EXISTS "idx_projects_project_status_id"
  ON "public"."projects" ("project_status_id");

CREATE INDEX IF NOT EXISTS "idx_projects_source_id"
  ON "public"."projects" ("source_id");

CREATE INDEX IF NOT EXISTS "idx_projects_customer"
  ON "public"."projects" ("customer");

CREATE INDEX IF NOT EXISTS "idx_projects_service"
  ON "public"."projects" ("service");

-- Partial index — only rows with a linked Drive folder
CREATE INDEX IF NOT EXISTS "idx_projects_drive_folder_id"
  ON "public"."projects" ("drive_folder_id")
  WHERE "drive_folder_id" IS NOT NULL;

-- Partial indexes for FK columns that will mostly be NULL initially
CREATE INDEX IF NOT EXISTS "idx_invoice_project_id"
  ON "public"."invoice" ("project_id")
  WHERE "project_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_quote_project_id"
  ON "public"."quote" ("project_id")
  WHERE "project_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_project_assignee_user_id"
  ON "public"."project_assignee" ("user_id");

-- -----------------------------------------------------------------
-- PHASE 9 — updated_at trigger on projects
-- (reuses the existing update_updated_at_column() function)
-- -----------------------------------------------------------------

CREATE OR REPLACE TRIGGER "update_projects_updated_at"
  BEFORE UPDATE ON "public"."projects"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();

-- -----------------------------------------------------------------
-- PHASE 10 — Row Level Security
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_status"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_source"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_assignee" ENABLE ROW LEVEL SECURITY;

-- projects — full CRUD for authenticated users
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'projects'
      AND  policyname = 'Enable all operations for authenticated users only'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable all operations for authenticated users only"
        ON public.projects
        TO authenticated
        USING (true)
        WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

-- project_status — read-only for authenticated users (managed via admin)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'project_status'
      AND  policyname = 'Enable read for authenticated users'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable read for authenticated users"
        ON public.project_status
        FOR SELECT
        TO authenticated
        USING (true)
    $policy$;
  END IF;
END;
$$;

-- project_source — read-only for authenticated users
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'project_source'
      AND  policyname = 'Enable read for authenticated users'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable read for authenticated users"
        ON public.project_source
        FOR SELECT
        TO authenticated
        USING (true)
    $policy$;
  END IF;
END;
$$;

-- project_assignee — full CRUD for authenticated users
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'project_assignee'
      AND  policyname = 'Enable all operations for authenticated users only'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable all operations for authenticated users only"
        ON public.project_assignee
        TO authenticated
        USING (true)
        WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 11 — project_type lookup table
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."project_type" (
    "id"          bigint                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        text                        NOT NULL UNIQUE,
    "description" text,
    "created_at"  timestamp with time zone    NOT NULL DEFAULT now(),
    "updated_at"  timestamp without time zone          DEFAULT now()
);

ALTER TABLE "public"."project_type" OWNER TO "postgres";
COMMENT ON TABLE "public"."project_type" IS 'Lookup table for the type of roofing project (Residential, Commercial, etc.).';

INSERT INTO "public"."project_type" ("id", "name", "description") VALUES
  (1, 'Residential',      'Single-family or multi-family residential property.'),
  (2, 'Commercial',       'Commercial or industrial building.'),
  (3, 'New Construction', 'New build — no existing roof to tear off.'),
  (4, 'Insurance Claim',  'Job driven by an insurance claim (hail, wind, storm damage).'),
  (5, 'Maintenance',      'Routine maintenance or minor repair.')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE "public"."project_type" ALTER COLUMN "id" RESTART WITH 6;

-- project_type_id FK on projects
ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "project_type_id" bigint
  REFERENCES "public"."project_type"("id") ON DELETE SET NULL;

COMMENT ON COLUMN "public"."projects"."project_type_id"
  IS 'FK to project_type. Classifies the project (Residential, Commercial, Insurance Claim, etc.).';

-- project_type — read-only for authenticated users
ALTER TABLE "public"."project_type" ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public'
      AND  tablename  = 'project_type'
      AND  policyname = 'Enable read for authenticated users'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable read for authenticated users"
        ON public.project_type
        FOR SELECT
        TO authenticated
        USING (true)
    $policy$;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 12 — Structured address + property owner + status default
--
-- Design principle: projects are identified by address first.
-- street_address is the canonical primary field. The legacy `address`
-- text column is kept for backward compatibility and should be kept
-- in sync by application code.
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "street_address"      text,
  ADD COLUMN IF NOT EXISTS "city"                text,
  ADD COLUMN IF NOT EXISTS "state"               text,
  ADD COLUMN IF NOT EXISTS "zipcode"             text,
  ADD COLUMN IF NOT EXISTS "property_owner_name" text;

COMMENT ON COLUMN "public"."projects"."street_address"
  IS 'Primary project identifier. Required for all new projects. Populated via Google Maps Places autocomplete.';
COMMENT ON COLUMN "public"."projects"."city"
  IS 'City of the job site.';
COMMENT ON COLUMN "public"."projects"."state"
  IS 'State of the job site (2-letter code, e.g. TX).';
COMMENT ON COLUMN "public"."projects"."zipcode"
  IS 'Zip/postal code of the job site.';
COMMENT ON COLUMN "public"."projects"."property_owner_name"
  IS 'Free-text property owner name. Used before a full Customer record is created.';

-- Back-fill structured address from the legacy unstructured column
UPDATE "public"."projects"
SET    "street_address" = "address"
WHERE  "street_address" IS NULL AND "address" IS NOT NULL;

-- Set a default on the legacy status column to prevent INSERT failures
ALTER TABLE "public"."projects"
  ALTER COLUMN "status" SET DEFAULT 'Lead';

-- -----------------------------------------------------------------
-- PHASE 13 — Insurance claim & permit fields
-- -----------------------------------------------------------------

-- Insurance claim tracking (common in hail / storm damage roofing)
ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "is_insurance_claim" boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "claim_number"       text,
  ADD COLUMN IF NOT EXISTS "insurance_company"  text,
  ADD COLUMN IF NOT EXISTS "adjuster_name"      text,
  ADD COLUMN IF NOT EXISTS "adjuster_phone"     text,
  ADD COLUMN IF NOT EXISTS "date_of_loss"       date;

COMMENT ON COLUMN "public"."projects"."is_insurance_claim"
  IS 'True when the project is driven by an insurance claim (hail, wind, storm damage).';
COMMENT ON COLUMN "public"."projects"."claim_number"
  IS 'Insurance claim reference number.';
COMMENT ON COLUMN "public"."projects"."insurance_company"
  IS 'Name of the insurance carrier handling the claim.';
COMMENT ON COLUMN "public"."projects"."adjuster_name"
  IS 'Name of the insurance adjuster assigned to this claim.';
COMMENT ON COLUMN "public"."projects"."adjuster_phone"
  IS 'Phone number for the insurance adjuster.';
COMMENT ON COLUMN "public"."projects"."date_of_loss"
  IS 'Date the damage event (storm, hail, etc.) occurred.';

-- Permit tracking
ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "permit_required"    boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "permit_number"      text,
  ADD COLUMN IF NOT EXISTS "permit_issued_date" date;

COMMENT ON COLUMN "public"."projects"."permit_required"
  IS 'True when a permit is required for this project.';
COMMENT ON COLUMN "public"."projects"."permit_number"
  IS 'Permit number issued by the local authority.';
COMMENT ON COLUMN "public"."projects"."permit_issued_date"
  IS 'Date the permit was issued.';

-- -----------------------------------------------------------------
-- PHASE 14 — Financial & measurement fields + quote_request link
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "estimated_value"   numeric(12,2),
  ADD COLUMN IF NOT EXISTS "contract_amount"   numeric(12,2),
  ADD COLUMN IF NOT EXISTS "sq_ft_measurement" text;

COMMENT ON COLUMN "public"."projects"."estimated_value"
  IS 'Estimated project value before a contract is signed.';
COMMENT ON COLUMN "public"."projects"."contract_amount"
  IS 'Agreed contract amount once the customer has approved the job.';
COMMENT ON COLUMN "public"."projects"."sq_ft_measurement"
  IS 'Roof square footage measurement used for estimating.';

-- Link project back to originating web quote request (closes web-form → project loop)
ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "quote_request_id" bigint
  REFERENCES "public"."quote_request"("id") ON DELETE SET NULL;

COMMENT ON COLUMN "public"."projects"."quote_request_id"
  IS 'FK to quote_request. Traces this project back to the original web form submission.';

-- -----------------------------------------------------------------
-- PHASE 15 — Defensive constraints
-- -----------------------------------------------------------------

-- UNIQUE on project_status.name (prevents duplicate status rows)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'project_status_name_key'
      AND  conrelid = 'public.project_status'::regclass
  ) THEN
    ALTER TABLE public.project_status ADD CONSTRAINT project_status_name_key UNIQUE (name);
  END IF;
END;
$$;

-- UNIQUE on project_source.name
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'project_source_name_key'
      AND  conrelid = 'public.project_source'::regclass
  ) THEN
    ALTER TABLE public.project_source ADD CONSTRAINT project_source_name_key UNIQUE (name);
  END IF;
END;
$$;

-- CHECK: end_date must not precede start_date
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'projects_dates_check'
      AND  conrelid = 'public.projects'::regclass
  ) THEN
    ALTER TABLE public.projects
      ADD CONSTRAINT projects_dates_check
      CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date);
  END IF;
END;
$$;

-- NOT NULL on project_number (safe after IDENTITY + back-fill in Phase 4)
DO $$
DECLARE
  v_is_nullable text;
BEGIN
  SELECT is_nullable INTO v_is_nullable
  FROM   information_schema.columns
  WHERE  table_schema = 'public'
    AND  table_name   = 'projects'
    AND  column_name  = 'project_number';

  IF v_is_nullable = 'YES' THEN
    ALTER TABLE public.projects ALTER COLUMN project_number SET NOT NULL;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 16 — Indexes for new columns
-- -----------------------------------------------------------------

CREATE INDEX IF NOT EXISTS "idx_projects_project_type_id"
  ON "public"."projects" ("project_type_id");

CREATE INDEX IF NOT EXISTS "idx_projects_is_insurance_claim"
  ON "public"."projects" ("is_insurance_claim")
  WHERE "is_insurance_claim" = true;

CREATE INDEX IF NOT EXISTS "idx_projects_quote_request_id"
  ON "public"."projects" ("quote_request_id")
  WHERE "quote_request_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_projects_city"
  ON "public"."projects" ("city");

CREATE INDEX IF NOT EXISTS "idx_projects_state"
  ON "public"."projects" ("state");

COMMIT;

ROLLBACK;
