# FROM nginx:alpine
# COPY build /usr/share/nginx/html

FROM node:16.14.2 AS build
WORKDIR /build

COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install

COPY public/ public
COPY src/ src
COPY index.html index.html
COPY vite.config.js vite.config.js
COPY .env .
RUN npm run build

FROM nginx:alpine
COPY ./etc/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /build/dist/ /usr/share/nginx/html