// export { default as Login } from './Login';
// export { default as Signup } from './Signup';
// export { default as Dashboard } from './Dashboard/Dashboard';
// export { default as QuoteRequests } from './QuoteRequests/QuoteRequests';
// export { default as Invoices } from './Invoices/Invoices';
// export { default as InvoiceDetails } from './Invoices/InvoiceDetails';
// export { default as Quotes } from './Quotes/Quotes';
// export { default as QuoteById } from './Quotes/QuoteDetails';
// export { default as Customers } from './Customers/Customers';
// export { default as CustomerById } from './Customers/CustomerDetails';
export { default as LoginPage } from './login-page';
export { default as DashboardPage } from './dashboard-page';
export { default as CustomerPage } from './customers-page';
export { default as JobsPage } from './jobs-page';
export { default as QuotesPage } from './quotes-page';
export { default as InvoicesPage } from './invoices-page';
export { default as InboxPage } from './sales-leads-page';
export { default as CustomerInfoPage } from './customer-info-page';
export { default as DataManagementPage } from './data-management-page';
export { default as ServicesManagementPage } from './services-management-page';
export { default as StatusManagementPage } from './status-management-page';
export { default as PageNotFound } from './page-not-found';
