-- =================================================================
-- Migration: Projects Feature (Production)
-- Target:    supabase/prod (Postgres 15 / Supabase)
-- Date:      2026-05-19
-- Includes:  20260519 + 20260525 (sort_order) + 20260526 (RLS fixes)
--
-- Difference from dev version: Phase 0 creates the base projects
-- table first, since production does not have it yet.
--
-- SAFE TO RE-RUN: all DDL uses IF NOT EXISTS / idempotent DO $$ blocks.
-- ADDITIVE ONLY — no existing columns or rows are removed.
-- =================================================================

BEGIN;

-- -----------------------------------------------------------------
-- PHASE 0 — Base projects table (not present in production yet)
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."projects" (
    "id"             uuid                        DEFAULT gen_random_uuid() NOT NULL,
    "project_number" bigint,
    "address"        text                        NOT NULL DEFAULT '',
    "start_date"     date,
    "end_date"       date,
    "status"         text                        NOT NULL DEFAULT 'Lead',
    "service"        bigint,
    "customer"       bigint,
    "updated_at"     timestamp without time zone NOT NULL DEFAULT now(),
    "created_at"     timestamp with time zone    NOT NULL DEFAULT now(),
    CONSTRAINT "projects_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "public"."projects" OWNER TO "postgres";
COMMENT ON TABLE "public"."projects" IS 'This stores all the roofing projects that we are working on.';

-- FK: projects.service → service(id)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'projects_service_fkey'
      AND  conrelid = 'public.projects'::regclass
  ) THEN
    ALTER TABLE public.projects
      ADD CONSTRAINT projects_service_fkey
      FOREIGN KEY (service) REFERENCES public.service(id) ON DELETE SET NULL;
  END IF;
END;
$$;

-- FK: projects.customer → customer(id)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'projects_customer_fkey'
      AND  conrelid = 'public.projects'::regclass
  ) THEN
    ALTER TABLE public.projects
      ADD CONSTRAINT projects_customer_fkey
      FOREIGN KEY (customer) REFERENCES public.customer(id) ON DELETE SET NULL;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 1 — project_status lookup table
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."project_status" (
    "id"          bigint                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        text                        NOT NULL,
    "description" text,
    "created_at"  timestamp with time zone    NOT NULL DEFAULT now(),
    "updated_at"  timestamp without time zone          DEFAULT now()
);

ALTER TABLE "public"."project_status" OWNER TO "postgres";
COMMENT ON TABLE "public"."project_status" IS 'Lookup table for project lifecycle statuses.';

INSERT INTO "public"."project_status" ("id", "name", "description") VALUES
  (1, 'Lead',                    'Potential customer — not yet committed.'),
  (2, 'Estimate Sent',           'Quote/proposal delivered, awaiting customer response.'),
  (3, 'Approved / Booked',       'Customer said yes — job is scheduled.'),
  (4, 'In Progress',             'Crew is actively working on the roof.'),
  (5, 'Inspection / Punch List', 'Work done — final walkthrough or touch-ups needed.'),
  (6, 'Invoice Sent',            'Waiting on payment.'),
  (7, 'Completed',               'Paid and closed.')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE "public"."project_status" ALTER COLUMN "id" RESTART WITH 8;

-- -----------------------------------------------------------------
-- PHASE 2 — project_source lookup table
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."project_source" (
    "id"          bigint                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        text                        NOT NULL,
    "description" text,
    "created_at"  timestamp with time zone    NOT NULL DEFAULT now(),
    "updated_at"  timestamp without time zone          DEFAULT now()
);

ALTER TABLE "public"."project_source" OWNER TO "postgres";
COMMENT ON TABLE "public"."project_source" IS 'Lookup table for how a project was sourced or acquired.';

INSERT INTO "public"."project_source" ("id", "name", "description") VALUES
  (1, 'Referral',                 'Project came from a customer or partner referral.'),
  (2, 'Repeat Customer',          'Returning customer from a previous roofing job.'),
  (3, 'Quote Request / Web Form', 'Customer submitted an online quote request form.'),
  (4, 'Walk-in',                  'Customer contacted the company directly.'),
  (5, 'Social Media',             'Project originated through social media channels.'),
  (6, 'Other',                    'Source not covered by the options above.')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE "public"."project_source" ALTER COLUMN "id" RESTART WITH 7;

-- -----------------------------------------------------------------
-- PHASE 3 — Enhance projects table: status FK + source FK + rich text
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "project_status_id" bigint
  REFERENCES "public"."project_status"("id") ON DELETE SET NULL;

COMMENT ON COLUMN "public"."projects"."project_status_id"
  IS 'FK to project_status. Replaces the raw status text column over time.';

UPDATE "public"."projects" p
SET    "project_status_id" = ps.id
FROM   "public"."project_status" ps
WHERE  LOWER(TRIM(p.status)) = LOWER(ps.name)
  AND  p.project_status_id IS NULL;

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "source_id" bigint
  REFERENCES "public"."project_source"("id") ON DELETE SET NULL;

COMMENT ON COLUMN "public"."projects"."source_id"
  IS 'FK to project_source. Tracks how this project was acquired.';

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "notes"       text;

-- -----------------------------------------------------------------
-- PHASE 4 — project_number: UNIQUE constraint + auto-increment identity
-- -----------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname    = 'projects_project_number_key'
      AND  conrelid   = 'public.projects'::regclass
  ) THEN
    ALTER TABLE public.projects
      ADD CONSTRAINT projects_project_number_key UNIQUE (project_number);
  END IF;
END;
$$;

DO $$
DECLARE
  v_identity_gen text;
  v_next         bigint;
  v_max_num      bigint;
BEGIN
  SELECT identity_generation INTO v_identity_gen
  FROM   information_schema.columns
  WHERE  table_schema = 'public'
    AND  table_name   = 'projects'
    AND  column_name  = 'project_number';

  IF v_identity_gen IS NULL THEN
    -- Backfill any NULL project_number rows before enforcing NOT NULL
    SELECT COALESCE(MAX(project_number), 0) INTO v_max_num FROM public.projects;
    WITH numbered AS (
      SELECT id, v_max_num + ROW_NUMBER() OVER () AS new_num
      FROM public.projects
      WHERE project_number IS NULL
    )
    UPDATE public.projects p
    SET    project_number = numbered.new_num
    FROM   numbered
    WHERE  p.id = numbered.id;

    -- GENERATED AS IDENTITY requires NOT NULL
    ALTER TABLE public.projects ALTER COLUMN project_number SET NOT NULL;
    ALTER TABLE public.projects
      ALTER COLUMN project_number ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;

  SELECT identity_generation INTO v_identity_gen
  FROM   information_schema.columns
  WHERE  table_schema = 'public'
    AND  table_name   = 'projects'
    AND  column_name  = 'project_number';

  IF v_identity_gen IS NOT NULL THEN
    SELECT COALESCE(MAX(project_number), 0) + 1 INTO v_next
    FROM   public.projects;

    EXECUTE format(
      'ALTER TABLE public.projects ALTER COLUMN project_number RESTART WITH %s',
      v_next
    );
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 5 — Google Drive columns
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "drive_folder_id"   text,
  ADD COLUMN IF NOT EXISTS "drive_folder_name" text,
  ADD COLUMN IF NOT EXISTS "drive_folder_url"  text;

-- -----------------------------------------------------------------
-- PHASE 6 — project_assignee junction table
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."project_assignee" (
    "project_id"  uuid                     NOT NULL,
    "user_id"     uuid                     NOT NULL,
    "assigned_at" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "project_assignee_pkey" PRIMARY KEY ("project_id", "user_id")
);

ALTER TABLE "public"."project_assignee" OWNER TO "postgres";

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'project_assignee_project_id_fkey'
      AND  conrelid = 'public.project_assignee'::regclass
  ) THEN
    ALTER TABLE public.project_assignee
      ADD CONSTRAINT project_assignee_project_id_fkey
      FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'project_assignee_user_id_fkey'
      AND  conrelid = 'public.project_assignee'::regclass
  ) THEN
    ALTER TABLE public.project_assignee
      ADD CONSTRAINT project_assignee_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 7 — Link invoice & quote to project
-- -----------------------------------------------------------------

ALTER TABLE "public"."invoice"
  ADD COLUMN IF NOT EXISTS "project_id" uuid;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'invoice_project_id_fkey'
      AND  conrelid = 'public.invoice'::regclass
  ) THEN
    ALTER TABLE public.invoice
      ADD CONSTRAINT invoice_project_id_fkey
      FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
  END IF;
END;
$$;

ALTER TABLE "public"."quote"
  ADD COLUMN IF NOT EXISTS "project_id" uuid;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE  conname  = 'quote_project_id_fkey'
      AND  conrelid = 'public.quote'::regclass
  ) THEN
    ALTER TABLE public.quote
      ADD CONSTRAINT quote_project_id_fkey
      FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 8 — Indexes
-- -----------------------------------------------------------------

CREATE INDEX IF NOT EXISTS "idx_projects_project_status_id"
  ON "public"."projects" ("project_status_id");

CREATE INDEX IF NOT EXISTS "idx_projects_source_id"
  ON "public"."projects" ("source_id");

CREATE INDEX IF NOT EXISTS "idx_projects_customer"
  ON "public"."projects" ("customer");

CREATE INDEX IF NOT EXISTS "idx_projects_service"
  ON "public"."projects" ("service");

CREATE INDEX IF NOT EXISTS "idx_projects_drive_folder_id"
  ON "public"."projects" ("drive_folder_id")
  WHERE "drive_folder_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_invoice_project_id"
  ON "public"."invoice" ("project_id")
  WHERE "project_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_quote_project_id"
  ON "public"."quote" ("project_id")
  WHERE "project_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_project_assignee_user_id"
  ON "public"."project_assignee" ("user_id");

-- -----------------------------------------------------------------
-- PHASE 9 — updated_at trigger on projects
-- -----------------------------------------------------------------

CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER "update_projects_updated_at"
  BEFORE UPDATE ON "public"."projects"
  FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();

-- -----------------------------------------------------------------
-- PHASE 10 — Row Level Security
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"         ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_status"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_source"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_assignee" ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public' AND tablename = 'projects'
      AND  policyname = 'Enable all operations for authenticated users only'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable all operations for authenticated users only"
        ON public.projects TO authenticated USING (true) WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public' AND tablename = 'project_status'
      AND  policyname = 'Enable read for authenticated users'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable read for authenticated users"
        ON public.project_status FOR SELECT TO authenticated USING (true)
    $policy$;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public' AND tablename = 'project_source'
      AND  policyname = 'Enable read for authenticated users'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable read for authenticated users"
        ON public.project_source FOR SELECT TO authenticated USING (true)
    $policy$;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public' AND tablename = 'project_assignee'
      AND  policyname = 'Enable all operations for authenticated users only'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable all operations for authenticated users only"
        ON public.project_assignee TO authenticated USING (true) WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 11 — project_type lookup table
-- -----------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "public"."project_type" (
    "id"          bigint                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"        text                        NOT NULL UNIQUE,
    "description" text,
    "created_at"  timestamp with time zone    NOT NULL DEFAULT now(),
    "updated_at"  timestamp without time zone          DEFAULT now()
);

ALTER TABLE "public"."project_type" OWNER TO "postgres";

INSERT INTO "public"."project_type" ("id", "name", "description") VALUES
  (1, 'Residential',      'Single-family or multi-family residential property.'),
  (2, 'Commercial',       'Commercial or industrial building.'),
  (3, 'New Construction', 'New build — no existing roof to tear off.'),
  (4, 'Insurance Claim',  'Job driven by an insurance claim (hail, wind, storm damage).'),
  (5, 'Maintenance',      'Routine maintenance or minor repair.')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE "public"."project_type" ALTER COLUMN "id" RESTART WITH 6;

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "project_type_id" bigint
  REFERENCES "public"."project_type"("id") ON DELETE SET NULL;

ALTER TABLE "public"."project_type" ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE  schemaname = 'public' AND tablename = 'project_type'
      AND  policyname = 'Enable read for authenticated users'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "Enable read for authenticated users"
        ON public.project_type FOR SELECT TO authenticated USING (true)
    $policy$;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 12 — Structured address + property owner + status default
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "street_address"      text,
  ADD COLUMN IF NOT EXISTS "city"                text,
  ADD COLUMN IF NOT EXISTS "state"               text,
  ADD COLUMN IF NOT EXISTS "zipcode"             text,
  ADD COLUMN IF NOT EXISTS "property_owner_name" text;

UPDATE "public"."projects"
SET    "street_address" = "address"
WHERE  "street_address" IS NULL AND "address" IS NOT NULL;

ALTER TABLE "public"."projects"
  ALTER COLUMN "status" SET DEFAULT 'Lead';

-- -----------------------------------------------------------------
-- PHASE 13 — Insurance claim & permit fields
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "is_insurance_claim" boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "claim_number"       text,
  ADD COLUMN IF NOT EXISTS "insurance_company"  text,
  ADD COLUMN IF NOT EXISTS "adjuster_name"      text,
  ADD COLUMN IF NOT EXISTS "adjuster_phone"     text,
  ADD COLUMN IF NOT EXISTS "date_of_loss"       date,
  ADD COLUMN IF NOT EXISTS "permit_required"    boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "permit_number"      text,
  ADD COLUMN IF NOT EXISTS "permit_issued_date" date;

-- -----------------------------------------------------------------
-- PHASE 14 — Financial & measurement fields + quote_request link
-- -----------------------------------------------------------------

ALTER TABLE "public"."projects"
  ADD COLUMN IF NOT EXISTS "estimated_value"   numeric(12,2),
  ADD COLUMN IF NOT EXISTS "contract_amount"   numeric(12,2),
  ADD COLUMN IF NOT EXISTS "sq_ft_measurement" text;

-- Only add quote_request_id FK if the quote_request table exists
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'quote_request'
  ) THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'projects'
        AND column_name = 'quote_request_id'
    ) THEN
      ALTER TABLE public.projects
        ADD COLUMN "quote_request_id" bigint
        REFERENCES public.quote_request(id) ON DELETE SET NULL;
    END IF;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 15 — Defensive constraints
-- -----------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'project_status_name_key' AND conrelid = 'public.project_status'::regclass
  ) THEN
    ALTER TABLE public.project_status ADD CONSTRAINT project_status_name_key UNIQUE (name);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'project_source_name_key' AND conrelid = 'public.project_source'::regclass
  ) THEN
    ALTER TABLE public.project_source ADD CONSTRAINT project_source_name_key UNIQUE (name);
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'projects_dates_check' AND conrelid = 'public.projects'::regclass
  ) THEN
    ALTER TABLE public.projects
      ADD CONSTRAINT projects_dates_check
      CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date);
  END IF;
END;
$$;

DO $$
DECLARE
  v_is_nullable text;
BEGIN
  SELECT is_nullable INTO v_is_nullable
  FROM   information_schema.columns
  WHERE  table_schema = 'public' AND table_name = 'projects' AND column_name = 'project_number';

  IF v_is_nullable = 'YES' THEN
    ALTER TABLE public.projects ALTER COLUMN project_number SET NOT NULL;
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- PHASE 16 — Indexes for new columns
-- -----------------------------------------------------------------

CREATE INDEX IF NOT EXISTS "idx_projects_project_type_id"
  ON "public"."projects" ("project_type_id");

CREATE INDEX IF NOT EXISTS "idx_projects_is_insurance_claim"
  ON "public"."projects" ("is_insurance_claim")
  WHERE "is_insurance_claim" = true;

CREATE INDEX IF NOT EXISTS "idx_projects_quote_request_id"
  ON "public"."projects" ("quote_request_id")
  WHERE "quote_request_id" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "idx_projects_city"  ON "public"."projects" ("city");
CREATE INDEX IF NOT EXISTS "idx_projects_state" ON "public"."projects" ("state");

-- -----------------------------------------------------------------
-- PHASE 17 — sort_order column on project_status (from 20260525)
-- -----------------------------------------------------------------

ALTER TABLE project_status ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;

UPDATE project_status SET sort_order = id WHERE sort_order = 0;

-- Plain index for ORDER BY performance (not unique — avoids deadlocks on swap)
CREATE INDEX IF NOT EXISTS project_status_sort_order_idx ON project_status (sort_order);

-- -----------------------------------------------------------------
-- PHASE 18 — project_status write policies (from 20260526)
-- -----------------------------------------------------------------

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'project_status'
      AND policyname = 'authenticated_can_update_project_status'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "authenticated_can_update_project_status"
        ON project_status FOR UPDATE TO authenticated USING (true) WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'project_status'
      AND policyname = 'authenticated_can_insert_project_status'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "authenticated_can_insert_project_status"
        ON project_status FOR INSERT TO authenticated WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'project_status'
      AND policyname = 'authenticated_can_delete_project_status'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "authenticated_can_delete_project_status"
        ON project_status FOR DELETE TO authenticated USING (true)
    $policy$;
  END IF;
END;
$$;

-- Same write policies for project_source and project_type
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'project_source'
      AND policyname = 'authenticated_can_update_project_source'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "authenticated_can_update_project_source"
        ON project_source FOR UPDATE TO authenticated USING (true) WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'project_source'
      AND policyname = 'authenticated_can_insert_project_source'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "authenticated_can_insert_project_source"
        ON project_source FOR INSERT TO authenticated WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'project_source'
      AND policyname = 'authenticated_can_delete_project_source'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "authenticated_can_delete_project_source"
        ON project_source FOR DELETE TO authenticated USING (true)
    $policy$;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'project_type'
      AND policyname = 'authenticated_can_update_project_type'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "authenticated_can_update_project_type"
        ON project_type FOR UPDATE TO authenticated USING (true) WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'project_type'
      AND policyname = 'authenticated_can_insert_project_type'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "authenticated_can_insert_project_type"
        ON project_type FOR INSERT TO authenticated WITH CHECK (true)
    $policy$;
  END IF;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'project_type'
      AND policyname = 'authenticated_can_delete_project_type'
  ) THEN
    EXECUTE $policy$
      CREATE POLICY "authenticated_can_delete_project_type"
        ON project_type FOR DELETE TO authenticated USING (true)
    $policy$;
  END IF;
END;
$$;

COMMIT;
ROLLBACK; -- Remove this line to apply the migration permanently
